import 'package:isar/isar.dart';

part 'eod_entry.g.dart';

/// ISAR collection for end-of-day summary entries.
/// One entry per day, written by EodPipelineService.
/// Stores the condensed daily summary, correlation findings, and flags.
@Collection()
class EodEntry {
  Id id = Isar.autoIncrement;

  /// ISO 8601 date string (e.g. "2026-03-21").
  /// Unique per day.
  @Index(unique: true, replace: true)
  late String date;

  /// User-facing summary text generated by Gemma2b or Gemini.
  late String summaryText;

  /// Correlation summary from the model's JSON block.
  String? correlationSummary;

  /// Whether the EOD analysis flagged something for attention.
  @Index()
  late bool flagged;

  /// Reason for the flag (if flagged = true).
  String? flagReason;

  /// Whether a RAG-matched condition was surfaced (Gemini online only).
  String? ragMatch;

  /// Daily fitness score snapshot used in this EOD analysis.
  late double fitnessScore;

  /// Number of mood log entries processed today.
  late int moodEntryCount;

  /// Whether this EOD was generated online (Gemini) or offline (Gemma2b).
  late bool generatedOnline;

  /// Full UTC timestamp of when this EOD was run.
  @Index()
  late DateTime timestamp;
}
